DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [3432]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [8260]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:module 'hashlib' has no attribute 'pkdf2_hmac'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\register\route.py", line 23, in user_data
    function_response = await register.get_headers(json_dict)
  File "D:\Data_Science_Python_Programs1\fastapi_project\register\register.py", line 24, in get_headers
    hashed_json_password = hashlib.pkdf2_hmac('sha512', bytes(json_dict['password'], 'utf-8'),
AttributeError: module 'hashlib' has no attribute 'pkdf2_hmac'
INFO:root:{'response': {'message': 'AttributeError has been occurred', 'error': '(<class \'AttributeError\'>, AttributeError("module \'hashlib\' has no attribute \'pkdf2_hmac\'")) error line = 23', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [9040]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [14504]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [14096]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [9268]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [16388]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:cannot encode object: Header(user_agent), of type: <class 'fastapi.params.Header'>
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\route.py", line 24, in login_data
    function_response = await auth.login_func(json_dict['emailId'], json_dict['password'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 51, in login_func
    await insert_val({"user_id": record['_id'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 27, in insert_val
    user_session.insert_one(json)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 705, in insert_one
    self._insert(document,
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 620, in _insert
    return self._insert_one(
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    result = sock_info.command(
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 726, in command
    self._raise_connection_failure(error)
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "C:\Python39\lib\site-packages\pymongo\network.py", line 118, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "C:\Python39\lib\site-packages\pymongo\message.py", line 742, in _op_msg
    return _op_msg_uncompressed(
bson.errors.InvalidDocument: cannot encode object: Header(user_agent), of type: <class 'fastapi.params.Header'>
INFO:root:{'response': {'message': 'bson.errors.InvalidDocument has been occurred', 'error': '(<class \'bson.errors.InvalidDocument\'>, InvalidDocument("cannot encode object: Header(user_agent), of type: <class \'fastapi.params.Header\'>")) error line = 24', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [3724]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:cannot encode object: Header(user_agent), of type: <class 'fastapi.params.Header'>
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\route.py", line 24, in login_data
    function_response = await auth.login_func(json_dict['emailId'], json_dict['password'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 51, in login_func
    await insert_val({"user_id": record['_id'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 27, in insert_val
    user_session.insert_one(json)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 705, in insert_one
    self._insert(document,
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 620, in _insert
    return self._insert_one(
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    result = sock_info.command(
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 726, in command
    self._raise_connection_failure(error)
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "C:\Python39\lib\site-packages\pymongo\network.py", line 118, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "C:\Python39\lib\site-packages\pymongo\message.py", line 742, in _op_msg
    return _op_msg_uncompressed(
bson.errors.InvalidDocument: cannot encode object: Header(user_agent), of type: <class 'fastapi.params.Header'>
INFO:root:{'response': {'message': 'bson.errors.InvalidDocument has been occurred', 'error': '(<class \'bson.errors.InvalidDocument\'>, InvalidDocument("cannot encode object: Header(user_agent), of type: <class \'fastapi.params.Header\'>")) error line = 24', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [15752]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python39\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Python39\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Python39\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Python39\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Python39\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Python39\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\route.py", line 24, in login_data
    function_response = await auth.login_func(json_dict['emailId'], json_dict['password'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 51, in login_func
    await insert_val({"user_id": record['_id'],
  File "D:\Data_Science_Python_Programs1\fastapi_project\login\auth.py", line 27, in insert_val
    user_session.insert_one(json)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 705, in insert_one
    self._insert(document,
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 620, in _insert
    return self._insert_one(
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "C:\Python39\lib\site-packages\pymongo\collection.py", line 597, in _insert_command
    result = sock_info.command(
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 726, in command
    self._raise_connection_failure(error)
  File "C:\Python39\lib\site-packages\pymongo\pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "C:\Python39\lib\site-packages\pymongo\network.py", line 118, in command
    request_id, msg, size, max_doc_size = message._op_msg(
  File "C:\Python39\lib\site-packages\pymongo\message.py", line 742, in _op_msg
    return _op_msg_uncompressed(
bson.errors.InvalidDocument: cannot encode object: Header(user_agent), of type: <class 'fastapi.params.Header'>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [9688]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [1640]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [5956]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [12776]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [10096]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [14992]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [14716]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [15868]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [13592]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:'token'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 20, in create_product
    header_token = json_data.headers['token']
  File "C:\Python39\lib\site-packages\starlette\datastructures.py", line 550, in __getitem__
    raise KeyError(key)
KeyError: 'token'
INFO:root:{'response': {'message': 'KeyError has been occurred', 'error': "(<class 'KeyError'>, KeyError('token')) error line = 20", 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [8020]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:'token'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 20, in create_product
    header_token = json_data.headers['token']
  File "C:\Python39\lib\site-packages\starlette\datastructures.py", line 550, in __getitem__
    raise KeyError(key)
KeyError: 'token'
INFO:root:{'response': {'message': 'KeyError has been occurred', 'error': "(<class 'KeyError'>, KeyError('token')) error line = 20", 'error_code': 'ER_UNK025'}, 'status': 'error'}
ERROR:root:'token'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 20, in create_product
    header_token = json_data.headers['token']
  File "C:\Python39\lib\site-packages\starlette\datastructures.py", line 550, in __getitem__
    raise KeyError(key)
KeyError: 'token'
INFO:root:{'response': {'message': 'KeyError has been occurred', 'error': "(<class 'KeyError'>, KeyError('token')) error line = 20", 'error_code': 'ER_UNK025'}, 'status': 'error'}
ERROR:root:'token'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 20, in create_product
    header_token = json_data.headers['token']
  File "C:\Python39\lib\site-packages\starlette\datastructures.py", line 550, in __getitem__
    raise KeyError(key)
KeyError: 'token'
INFO:root:{'response': {'message': 'KeyError has been occurred', 'error': "(<class 'KeyError'>, KeyError('token')) error line = 20", 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [11812]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [16784]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x000002113B2177C0>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [10688]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:{'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
INFO:root:<starlette.responses.JSONResponse object at 0x0000025EF6D12F10>
INFO:root:{'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
INFO:root:{'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [14352]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:{'response': {'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}}
INFO:root:<starlette.responses.JSONResponse object at 0x000001F95D9D1F10>
INFO:root:{'response': {'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [5948]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:{'response': {'error_code': 'ER_AUT009'}, 'status': 'error', 'message': 'validator.InvalidToken'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [4100]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:{'response': {}, 'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
INFO:root:{'response': {}, 'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
INFO:root:<starlette.responses.JSONResponse object at 0x000001B3457980D0>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [2132]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:{'status': 'error', 'message': 'validator.InvalidToken', 'error_code': 'ER_AUT009'}
INFO:root:<starlette.responses.JSONResponse object at 0x00000247B4052F10>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [10808]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x0000024FC0FF8D90>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [15520]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x000001B79A037D90>
INFO:root:<starlette.responses.JSONResponse object at 0x000001B79A022F10>
INFO:root:<starlette.responses.JSONResponse object at 0x000001B79A037190>
INFO:root:<starlette.responses.JSONResponse object at 0x000001B79A0379A0>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [1728]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:cannot encode object: dict_values(['4497659']), of type: <class 'dict_values'>
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 71, in get_product
    function_response = await operations.get_products(Uid)
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\operations.py", line 65, in get_products
    for record in fetched_records:
  File "C:\Python39\lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "C:\Python39\lib\site-packages\pymongo\cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "C:\Python39\lib\site-packages\pymongo\cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "C:\Python39\lib\site-packages\pymongo\mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "C:\Python39\lib\site-packages\pymongo\server.py", line 98, in run_operation
    message = operation.get_message(
  File "C:\Python39\lib\site-packages\pymongo\message.py", line 350, in get_message
    request_id, msg, size, _ = _op_msg(
  File "C:\Python39\lib\site-packages\pymongo\message.py", line 742, in _op_msg
    return _op_msg_uncompressed(
bson.errors.InvalidDocument: cannot encode object: dict_values(['4497659']), of type: <class 'dict_values'>
INFO:root:{'response': {'message': 'bson.errors.InvalidDocument has been occurred', 'error': '(<class \'bson.errors.InvalidDocument\'>, InvalidDocument("cannot encode object: dict_values([\'4497659\']), of type: <class \'dict_values\'>")) error line = 71', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [8176]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:'dict_values' object is not subscriptable
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 69, in get_product
    Uid = json_data.query_params.values()[0]
TypeError: 'dict_values' object is not subscriptable
INFO:root:{'response': {'message': 'TypeError has been occurred', 'error': '(<class \'TypeError\'>, TypeError("\'dict_values\' object is not subscriptable")) error line = 69', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [12896]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR:root:get() missing 1 required positional argument: 'key'
Traceback (most recent call last):
  File "D:\Data_Science_Python_Programs1\fastapi_project\operations\route.py", line 69, in get_product
    Uid = json_data.query_params.get()
TypeError: get() missing 1 required positional argument: 'key'
INFO:root:{'response': {'message': 'TypeError has been occurred', 'error': '(<class \'TypeError\'>, TypeError("get() missing 1 required positional argument: \'key\'")) error line = 69', 'error_code': 'ER_UNK025'}, 'status': 'error'}
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [15408]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x0000019A3A076DF0>
INFO:root:<starlette.responses.JSONResponse object at 0x0000019A3A076340>
INFO:root:<starlette.responses.JSONResponse object at 0x0000019A39EDF730>
INFO:root:<starlette.responses.JSONResponse object at 0x0000019A3A0A4850>
INFO:root:<starlette.responses.JSONResponse object at 0x0000019A3A0A49D0>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [11580]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x000001108F2D89D0>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [2644]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x0000019FA14E5970>
DEBUG:asyncio:Using selector: SelectSelector
INFO:uvicorn.error:Started server process [16196]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:root:<starlette.responses.JSONResponse object at 0x000001CF2AB91EE0>
INFO:root:<starlette.responses.JSONResponse object at 0x000001CF2AB91CD0>
INFO:root:<starlette.responses.JSONResponse object at 0x000001CF2AB91940>
INFO:root:<starlette.responses.JSONResponse object at 0x000001CF2ABB1D30>
